<header>
		<figure><a href="index.php"> <img src="images/Tabitha_Bike_Hire1.png" alt="Tabitha's Bike Hire" class="logo" /></a></figure>
		<!-- Bike Clipart taken from http://www.clipartpanda.com/categories/bicycle-clipart-->
	<nav>
		<ul id="nav">
			<li class="menu"><a href="index.php">INDEX</a></li> 
			<li class="menu"><a href="product.php">PRODUCT</a> </li>
			<li class="menu"><a href="enquire.php">ENQUIRE</a></li>
			<li class="menu"><a href="about.php">ABOUT</a></li>
			<li class="menu"><a href="enhancements.php">ENHANCEMENTS</a></li>
			<li class="menu"><a href="enhancements2.php">ENHANCEMENTS 2</a></li>
			<li class="menu"><a href="enhancements3.php">ENHANCEMENTS 3</a></li>
			<li class="menu"><a href="manager.php">MANAGER</a></li>
		</ul>
	</nav>
</header>